name: Rust CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

- name: Install Rust
  run: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: Check formatting
  run: |
    source $HOME/.cargo/env
    cargo fmt -- --check

- name: Build
  run: |
    source $HOME/.cargo/env
    cargo build --all --all-features --locked

- name: Clippy
  run: |
    source $HOME/.cargo/env
    cargo clippy --locked -- -D warnings

- name: Tests
  run: |
    source $HOME/.cargo/env
    cargo test --all --all-features --locked